name: "Render deploy service"

description: "Trigger a deploy of a Render service."
branding:
  icon: "package"
  color: "gray-dark"

inputs:
  serviceId:
    description: >-
      The ID of the service.
      See https://api-docs.render.com/reference/create-deploy.
    required: true
  apiKey:
    description: >-
      Authenticate all requests to the Render API with an API key. 
      See https://api-docs.render.com/reference/authentication.
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
